version: "3"

services:
  docs:
    build: .
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./docs:/app/docs
      - ./packages:/app/packages
      - ./website:/app/website
      - /app/website/build
      - ./node_modules:/app/node_modules
    command: pnpm website start --host 0.0.0.0

  verdaccio:
    image: verdaccio/verdaccio:latest
    volumes:
      # - ./verdaccio/storage:/verdaccio/storage:cached
      - './verdaccio/conf:/verdaccio/conf'
    ports:
      - "4873:4873"
    environment:
      - VERDACCIO_PUBLIC_URL=http://npm.local.dev:4873/
      - VIRTUAL_HOST=npm.local.dev
      - VIRTUAL_PORT=4873
      - VERDACCIO_USER_UID=1000
    networks:
      - reverseproxy

# volumes:
#   verdaccio:
#     driver: local

networks:
  reverseproxy:
    external: true
