name: Code Quality

on:
  pull_request:
    branches:
      - "master"
      - "chore/*"
      - "build/*"
      - "fix/*"
      - "feat/*"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
