name: Docs

on:
  pull_request:
    branches:
      - "master"
      - "chore/*"
      - "build/*"
      - "fix/*"
      - "feat/*"
    paths:
      - "website/*"


jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build Docs
        run: pnpm website build
