name: Pre-release

on:
  push:
    branches:
      - "chore/setup-release-please"

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/release-please
        id: pre-release
        if: github.event_name != 'pull_request'
        with:
          npm-registry-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          node-version: 22
          path: .
        env:
          MANIFEST: "false"