name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: yarn install

      - name: test
        run: yarn test

      - name: git login
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          yarn release --ci
