name: Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Install Packages
        run: yarn install

      - name: Test
        run: yarn test

      - name: Release
        run: yarn release
