name: Release

on:
  push:
    tags:
      - 'RELEASE-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: '0'
      - uses: actions/setup-node@v2
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: install dependencies
        run: npm run bootstrap-ci

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: git login
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm run release
          npm run npm-publish
