name: Release

on:
  push:
    branches:
      - master


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps
        with:
          hash: ${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: ./.github/actions/release-please
        id: release
        with:
          npm-registry-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 22
          path: .